name: Build and Release Java Ant Project

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Ant
      run: |
        cd PasswordGenerator
        ant compile jar

    - name: Release Executable JAR to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: PasswordGenerator/dist/*.jar
